services:
  - type: web
    name: trading-bbands-dashboard
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py
    plan: free
    envVars:
      - key: BINANCE_API_KEY
        sync: false
      - key: BINANCE_API_SECRET
        sync: false
      - key: TELEGRAM_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
    healthCheckPath: /
